### ISSUE TITLE
UI part

### ISSUE THREAD

**Issue by IvanKalabanan** [infinum/Android-Goldfinger#42]
Be cool if library will have simple dialog for check fingerprint. Like alert with title, message & status of check (success, failed)
Maybe something like that :
![image](https://user-images.githubusercontent.com/11329348/48415051-05c78b80-e755-11e8-9a47-653e71935f6c.png)

**Comment by domagojkorman** [comment]
Hi,

Google created [BiometricPrompt](https://medium.com/exploring-android/exploring-android-p-fingerprint-dialog-fa672ae62c6f) which is exactly what you want. We soon plan to integrate existing Goldfinger API with Google's new BiometricPrompt dialog.

**Comment by domagojkorman** [comment]
@IvanKalabanan It will be available via support library. That is as much as I know.

To keep it short, Goldfinger is not intended to solve UI related issues. 

While I do agree that it would be awesome that Goldfinger does everything, UI is something we did not want to implement in this library because it would bring more unnecessary issues.
