### ISSUE TITLE
How will this library handle devices without fingerprint but other biometric methods?

### ISSUE THREAD

**Issue by MinkiPani** [infinum/Android-Goldfinger#63]
Hi, I am just curious how this will behave on a device like Pixel 4XL?

Since it will only have face detection and no fingerprint, this library will show face detection prompt on runtime.

**Comment by igotepava** [comment]
Hello @MinkiPani!

`FingerprintManager` is replaced with `BiometricPrompt`which will show a prompt depeding on the type of biometric the device has. So for Pixel 4 that means that a prompt for face detection would be shown. You can read more about it [here](https://infinum.com/the-capsized-eight/new-and-improved-fingerprint-authentication-in-Android-apps).

**Comment by igotepava** [comment]
I'll close this, but if you have any more questions, do not hesitate to ask.

**Comment by TurKurT656** [comment]
what if a device doesn't have both?

**Comment by JonatanPlesko** [comment]
@TurKurT656 You can check whether authentication is possible with `canAuthenticate`. Check it out in the readme:
https://github.com/infinum/Android-Goldfinger#check-prerequisites

**Comment by RahulSDeshpande** [comment]
@igortepavac & @JonatanPlesko

For example, I have a device which supports fingerprint & face both & the user has enrolled it via device settings.
**Is there a way I can show both options & ask the user to chose & perform the authentication?**

Cheers!

**Comment by Aksi0m** [comment]
Hey @RahulSDeshpande !

I believe that is not possible at the time when you want to show the biometric prompt, but it might be different based on the device manufacturer. The method that will show by default is the one user has set as the primary biometric authentication type in the OS settings.

However with the new version of the library you can enforce users to use either weak or strong [authentication types](https://developer.android.com/reference/androidx/biometric/BiometricPrompt.PromptInfo.Builder#setAllowedAuthenticators(int)). Considering that most face/iris recognitions are considered weak biometric auth types and fingerprints as strong biometric auth types you have maybe some flexibility here to chose programmatically what to use, but I would not advise to use this as a long term solution since it is a hack rather then a solution.

I would advise you to use the new version of the library and let the OS handle the authentication type, in the end you really just want to know if the authentication failed or succeeded.

**Comment by RahulSDeshpande** [comment]
@Aksi0m Exactly!!
Thanks for the response!!
