### ISSUE TITLE
handle onCancel?

### ISSUE THREAD

**Issue by winnerawan** [infinum/Android-Goldfinger#71]
how to handle cancel ? 
```Goldfinger.Callback()``` only has ```onResult``` and ```onError```

**Comment by domagojkorman** [comment]
Hi @winnerawan ,

There are 2 different cancel types. First is if you manually call `cancel` method, second is if the User himself presses on the Cancel button.

In the first scenario, nothing will be triggered on the callback because if you cancel the authentication yourself, you don't want potential callback being triggered because it could leak and cause a crash while you are navigating to another screen.

In the second scenario, when the User cancels the authentication himself, you will get a callback to `onResult` with specific `USER_CANCELED` reason which can be found [here](https://github.com/infinum/Android-Goldfinger/blob/master/core/src/main/java/co/infinum/goldfinger/Goldfinger.java#L560).

I also suggest looking at other enumerations to see which other cases are covered.

**Comment by winnerawan** [comment]
Thanks for reply @domagojkorman
i think it's the second scenario, when dialog pop up shown, user choose cancel.
below code doesn't work, i dont get toast message
```java
if (result.reason()== Goldfinger.Reason.CANCELED) {
   Toast.makeText(getBaseActivity(), "CANCEL", Toast.LENGTH_SHORT).show();
}
```

**Comment by domagojkorman** [comment]
Did you try using `Goldfinger.Reason.USER_CANCELED`? The exact enum that I linked in my previous response - [here](https://github.com/infinum/Android-Goldfinger/blob/master/core/src/main/java/co/infinum/goldfinger/Goldfinger.java#L560)

**Comment by winnerawan** [comment]
Actually it's ```Goldfinger.Reason.NEGATIVE_BUTTON``` i think i need sleep and read it again, sorry, my bad.
case closed
